In [65]:
# Dependencies
import requests
import json
import pandas as pd
from pprint import pprint

In [66]:
# retrieve apis, and create jsons

urlRed = 'https://api.sampleapis.com/wines/reds'
urlWhite = 'https://api.sampleapis.com/wines/whites'
urlRose = 'https://api.sampleapis.com/wines/rose'
urlSparkling = 'https://api.sampleapis.com/wines/sparkling'
urlDessert = 'https://api.sampleapis.com/wines/dessert'
urlPort = 'https://api.sampleapis.com/wines/port'

redJson = requests.get(urlRed).json()
whiteJson = requests.get(urlWhite).json()
roseJson = requests.get(urlRose).json()
sparklingJson = requests.get(urlSparkling).json()
dessertJson = requests.get(urlDessert).json()
portJson = requests.get(urlPort).json()

In [67]:
# convert each json into a dataFrame
reds_df = pd.DataFrame(redJson)
whites_df = pd.DataFrame(whiteJson)
rose_df = pd.DataFrame(roseJson)
sparkling_df = pd.DataFrame(sparklingJson)
dessert_df = pd.DataFrame(dessertJson)
port_df = pd.DataFrame(portJson)

In [68]:
# check dataframes
reds_df.dtypes

winery      object
wine        object
rating      object
location    object
image       object
id           int64
average     object
dtype: object

In [69]:
# add column 'wine type'
reds_df["wine type"] = 'Red'
whites_df["wine type"] = 'White'
rose_df["wine type"] = 'Rose'
sparkling_df["wine type"] = 'Sparkling'
dessert_df["wine type"] = 'Dessert'
port_df["wine type"] = 'Port'

In [70]:
# check that columns were added
sparkling_df

,winery,wine,rating,location,image,id,wine type
0,Krug,Clos d'Ambonnay Blanc de Noirs Brut Champagne ...,"{'average': '4.9', 'reviews': '92 ratings'}",France\n·\nChampagne,https://images.vivino.com/thumbs/DPq0ayGPR4SBe...,1,Sparkling
1,Dom Pérignon,P2 Plénitude Brut Champagne 1995,"{'average': '4.9', 'reviews': '69 ratings'}",France\n·\nChampagne,https://images.vivino.com/thumbs/n5By4_iWSS2Zm...,2,Sparkling
2,Perrier-Jouët,Belle Epoque Brut Champagne 1979,"{'average': '4.9', 'reviews': '42 ratings'}",France\n·\nChampagne,https://images.vivino.com/thumbs/B976g0gBR1G4i...,3,Sparkling
3,Louis Roederer,Brut Premier Champagne 1993,"{'average': '4.9', 'reviews': '36 ratings'}",France\n·\nChampagne Premier Cru,https://images.vivino.com/thumbs/3PMfb042TN-5Z...,4,Sparkling
4,Dom Pérignon,Oenothèque Brut Champagne 1976,"{'average': '4.9', 'reviews': '31 ratings'}",France\n·\nChampagne,https://images.vivino.com/thumbs/-2XJ5LS9T0uFn...,5,Sparkling
...,...,...,...,...,...,...,...
731,Charles Heidsieck,Millesimé Brut Champagne 1999,"{'average': '4.5', 'reviews': '26 ratings'}",France\n·\nChampagne,https://images.vivino.com/thumbs/MwzrYHo3Tdedr...,732,Sparkling
732,Veuve Clicquot,La Grande Dame Brut Champagne 2010,"{'average': '4.5', 'reviews': '26 ratings'}",France\n·\nChampagne,https://images.vivino.com/thumbs/XRbzL1s9Q_qZw...,733,Sparkling
733,Vilmart & Cie,Cœur de Cuvée Champagne Premier Cru 2000,"{'average': '4.5', 'reviews': '26 ratings'}",France\n·\nChampagne Premier Cru,https://images.vivino.com/thumbs/ucR2sHrOR5epV...,734,Sparkling
734,Veuve Clicquot,Rare Vintage Brut Champagne 2011,"{'average': '4.5', 'reviews': '25 ratings'}",France\n·\nChampagne,https://images.vivino.com/thumbs/XjbCr0pLSNS30...,735,Sparkling
735,JCB (Jean-Charles Boisset),JCB No. 34 Brut Rosé N.V.,"{'average': '4.5', 'reviews': '25 ratings'}",United States\n·\nSonoma County,https://images.vivino.com/thumbs/-TzXkfqsRuWJ0...,736,Sparkling

In [71]:
# create new id keys
reds_df['id'] = ['r'+ '{:0>4}'.format(str(id)) for id in reds_df['id']]
whites_df['id'] = ['w'+ '{:0>4}'.format(str(id)) for id in whites_df['id']]
rose_df['id'] = ['o'+ '{:0>4}'.format(str(id)) for id in rose_df['id']]
sparkling_df['id'] = ['s'+ '{:0>4}'.format(str(id)) for id in sparkling_df['id']]
dessert_df['id'] = ['d'+ '{:0>4}'.format(str(id)) for id in dessert_df['id']]
port_df['id'] = ['p'+ '{:0>4}'.format(str(id)) for id in port_df['id']]

In [72]:
# check dataframes
whites_df

,winery,wine,rating,location,image,id,wine type
0,Domaine de La Romanée-Conti,Montrachet Grand Cru 2010,"{'average': '4.9', 'reviews': '37 ratings'}",France\n·\nMontrachet Grand Cru,https://images.vivino.com/thumbs/rORmihtxSrKG7...,w0001,White
1,Domaine de La Romanée-Conti,Montrachet Grand Cru 2014,"{'average': '4.9', 'reviews': '33 ratings'}",France\n·\nMontrachet Grand Cru,https://images.vivino.com/thumbs/rORmihtxSrKG7...,w0002,White
2,Domaine Coche-Dury,Meursault Les Rougeots 2001,"{'average': '4.9', 'reviews': '25 ratings'}",France\n·\nMeursault,https://images.vivino.com/thumbs/l5W5NRvZR_SzC...,w0003,White
3,Domaine Coche-Dury,Corton-Charlemagne Grand Cru N.V.,"{'average': '4.8', 'reviews': '416 ratings'}",France\n·\nCorton-Charlemagne Grand Cru,https://images.vivino.com/thumbs/ZGxHdQyGQt-hf...,w0004,White
4,Jarvis,Estate Finch Hollow Chardonnay (Cave Fermented...,"{'average': '4.8', 'reviews': '113 ratings'}",United States\n·\nNapa Valley,https://images.vivino.com/thumbs/pQ_92smWRKG7Y...,w0005,White
...,...,...,...,...,...,...,...
499,Domaine Leflaive,Chevalier-Montrachet Grand Cru 2015,"{'average': '4.6', 'reviews': '27 ratings'}",France\n·\nChevalier-Montrachet Grand Cru,https://images.vivino.com/thumbs/lD32nuv9Sw6sJ...,w0500,White
500,Château de Meursault,Puligny-Montrachet 1er Cru Champ Canet 2011,"{'average': '4.6', 'reviews': '27 ratings'}",France\n·\nPuligny-Montrachet Premier Cru,https://images.vivino.com/thumbs/cDjOBVU0QW-ur...,w0501,White
501,Domaine d'Auvenay (Lalou Bize Leroy),Auxey-Duresses 2004,"{'average': '4.6', 'reviews': '27 ratings'}",France\n·\nAuxey-Duresses,https://images.vivino.com/thumbs/OzI_mGYSQdCoy...,w0502,White
502,Penfolds,Yattarna Chardonnay (BIN 144) 2003,"{'average': '4.6', 'reviews': '27 ratings'}",Australia\n·\nAdelaide Hills,https://images.vivino.com/thumbs/aMdgLSKeQVybJ...,w0503,White
503,Pierre-Yves Colin-Morey,Chassagne-Montrachet Premier Cru Abbaye de Mor...,"{'average': '4.6', 'reviews': '27 ratings'}",France\n·\nChassagne-Montrachet 1er Cru 'Abbay...,https://images.vivino.com/thumbs/lj7yTJRLQoWN2...,w0504,White

In [73]:
# concatenate dataframes
wine_dataframes = [reds_df,whites_df,rose_df,sparkling_df,dessert_df,port_df]
wine_df = pd.concat(wine_dataframes)

In [74]:
# check combined wine_df
wine_df

,winery,wine,rating,location,image,id,average,wine type
0,Maselva,Emporda 2012,"{'average': '4.9', 'reviews': '88 ratings'}",Spain\n·\nEmpordà,https://images.vivino.com/thumbs/ApnIiXjcT5Kc3...,r0001,4.8,Red
1,Ernesto Ruffo,Amarone della Valpolicella Riserva N.V.,"{'average': '4.9', 'reviews': '75 ratings'}",Italy\n·\nAmarone della Valpolicella,https://images.vivino.com/thumbs/nC9V6L2mQQSq0...,r0002,NaN,Red
2,Cartuxa,Pêra-Manca Tinto 1990,"{'average': '4.9', 'reviews': '72 ratings'}",Portugal\n·\nAlentejo,https://images.vivino.com/thumbs/L33jsYUuTMWTM...,r0003,NaN,Red
3,Schrader,Cabernet Sauvignon RBS Beckstoffer To Kalon Vi...,"{'average': '4.9', 'reviews': '72 ratings'}",United States\n·\nOakville,https://images.vivino.com/thumbs/GpcSXs2ERS6ni...,r0004,NaN,Red
4,Hundred Acre,Wraith Cabernet Sauvignon 2013,"{'average': '4.9', 'reviews': '68 ratings'}",United States\n·\nNapa Valley,https://images.vivino.com/thumbs/PBhGMcRNQ7aVn...,r0005,NaN,Red
...,...,...,...,...,...,...,...,...
398,Toro Albalá,Don PX Gran Reserva 1986,"{'average': '4.4', 'reviews': '1077 ratings'}",Spain\n·\nMontilla-Moriles,https://images.vivino.com/thumbs/qAad7NzITH-si...,p0399,NaN,Port
399,Quinta do Vallado,Porto 20 Years Old Tawny N.V.,"{'average': '4.4', 'reviews': '1035 ratings'}",Portugal\n·\nPorto,https://images.vivino.com/thumbs/jHGhovW_QZ6b4...,p0400,NaN,Port
400,Quinta do Noval,Vintage Port N.V.,"{'average': '4.4', 'reviews': '1018 ratings'}",Portugal\n·\nVintage Port,https://images.vivino.com/thumbs/y9P75uaVT6yoG...,p0401,NaN,Port
401,Royal Oporto,20 Year Old Tawny Porto N.V.,"{'average': '4.4', 'reviews': '898 ratings'}",Portugal\n·\nAged Tawny Port,https://images.vivino.com/thumbs/4usgrqCrTUKag...,p0402,NaN,Port
402,Royal Oporto,Colheita Porto N.V.,"{'average': '4.4', 'reviews': '881 ratings'}",Portugal\n·\nColheita Port,https://images.vivino.com/thumbs/QnSyShsLRguoG...,p0403,NaN,Port

In [75]:
wine_df = wine_df.set_index('id')

In [76]:
# split location into 'country' and 'region'
wine_df[['country','region']] = wine_df.location.str.split('\\n·\\n', expand=True)

In [77]:
# checking dataframe
wine_df

,winery,wine,rating,location,image,average,wine type,country,region
id,,,,,,,,,
r0001,Maselva,Emporda 2012,"{'average': '4.9', 'reviews': '88 ratings'}",Spain\n·\nEmpordà,https://images.vivino.com/thumbs/ApnIiXjcT5Kc3...,4.8,Red,Spain,Empordà
r0002,Ernesto Ruffo,Amarone della Valpolicella Riserva N.V.,"{'average': '4.9', 'reviews': '75 ratings'}",Italy\n·\nAmarone della Valpolicella,https://images.vivino.com/thumbs/nC9V6L2mQQSq0...,NaN,Red,Italy,Amarone della Valpolicella
r0003,Cartuxa,Pêra-Manca Tinto 1990,"{'average': '4.9', 'reviews': '72 ratings'}",Portugal\n·\nAlentejo,https://images.vivino.com/thumbs/L33jsYUuTMWTM...,NaN,Red,Portugal,Alentejo
r0004,Schrader,Cabernet Sauvignon RBS Beckstoffer To Kalon Vi...,"{'average': '4.9', 'reviews': '72 ratings'}",United States\n·\nOakville,https://images.vivino.com/thumbs/GpcSXs2ERS6ni...,NaN,Red,United States,Oakville
r0005,Hundred Acre,Wraith Cabernet Sauvignon 2013,"{'average': '4.9', 'reviews': '68 ratings'}",United States\n·\nNapa Valley,https://images.vivino.com/thumbs/PBhGMcRNQ7aVn...,NaN,Red,United States,Napa Valley
...,...,...,...,...,...,...,...,...,...
p0399,Toro Albalá,Don PX Gran Reserva 1986,"{'average': '4.4', 'reviews': '1077 ratings'}",Spain\n·\nMontilla-Moriles,https://images.vivino.com/thumbs/qAad7NzITH-si...,NaN,Port,Spain,Montilla-Moriles
p0400,Quinta do Vallado,Porto 20 Years Old Tawny N.V.,"{'average': '4.4', 'reviews': '1035 ratings'}",Portugal\n·\nPorto,https://images.vivino.com/thumbs/jHGhovW_QZ6b4...,NaN,Port,Portugal,Porto
p0401,Quinta do Noval,Vintage Port N.V.,"{'average': '4.4', 'reviews': '1018 ratings'}",Portugal\n·\nVintage Port,https://images.vivino.com/thumbs/y9P75uaVT6yoG...,NaN,Port,Portugal,Vintage Port
p0402,Royal Oporto,20 Year Old Tawny Porto N.V.,"{'average': '4.4', 'reviews': '898 ratings'}",Portugal\n·\nAged Tawny Port,https://images.vivino.com/thumbs/4usgrqCrTUKag...,NaN,Port,Portugal,Aged Tawny Port
p0403,Royal Oporto,Colheita Porto N.V.,"{'average': '4.4', 'reviews': '881 ratings'}",Portugal\n·\nColheita Port,https://images.vivino.com/thumbs/QnSyShsLRguoG...,NaN,Port,Portugal,Colheita Port

In [78]:
# split rating into 'average rating' and 'review count'
#print(type(wine_df.iloc[0]['rating']))
averageRating = []
reviewCount = []

for index, wine in wine_df.iterrows():
    avg = wine['rating']['average']
    rev = wine['rating']['reviews']
    averageRating.append(float(avg))
    reviewCount.append(int(rev[:2]))

In [79]:
# adding 'average rating' and 'review count' columns
wine_df['average rating'] = averageRating
wine_df['review count'] = reviewCount

In [80]:
# checking dataframe
wine_df

,winery,wine,rating,location,image,average,wine type,country,region,average rating,review count
id,,,,,,,,,,,
r0001,Maselva,Emporda 2012,"{'average': '4.9', 'reviews': '88 ratings'}",Spain\n·\nEmpordà,https://images.vivino.com/thumbs/ApnIiXjcT5Kc3...,4.8,Red,Spain,Empordà,4.9,88
r0002,Ernesto Ruffo,Amarone della Valpolicella Riserva N.V.,"{'average': '4.9', 'reviews': '75 ratings'}",Italy\n·\nAmarone della Valpolicella,https://images.vivino.com/thumbs/nC9V6L2mQQSq0...,NaN,Red,Italy,Amarone della Valpolicella,4.9,75
r0003,Cartuxa,Pêra-Manca Tinto 1990,"{'average': '4.9', 'reviews': '72 ratings'}",Portugal\n·\nAlentejo,https://images.vivino.com/thumbs/L33jsYUuTMWTM...,NaN,Red,Portugal,Alentejo,4.9,72
r0004,Schrader,Cabernet Sauvignon RBS Beckstoffer To Kalon Vi...,"{'average': '4.9', 'reviews': '72 ratings'}",United States\n·\nOakville,https://images.vivino.com/thumbs/GpcSXs2ERS6ni...,NaN,Red,United States,Oakville,4.9,72
r0005,Hundred Acre,Wraith Cabernet Sauvignon 2013,"{'average': '4.9', 'reviews': '68 ratings'}",United States\n·\nNapa Valley,https://images.vivino.com/thumbs/PBhGMcRNQ7aVn...,NaN,Red,United States,Napa Valley,4.9,68
...,...,...,...,...,...,...,...,...,...,...,...
p0399,Toro Albalá,Don PX Gran Reserva 1986,"{'average': '4.4', 'reviews': '1077 ratings'}",Spain\n·\nMontilla-Moriles,https://images.vivino.com/thumbs/qAad7NzITH-si...,NaN,Port,Spain,Montilla-Moriles,4.4,10
p0400,Quinta do Vallado,Porto 20 Years Old Tawny N.V.,"{'average': '4.4', 'reviews': '1035 ratings'}",Portugal\n·\nPorto,https://images.vivino.com/thumbs/jHGhovW_QZ6b4...,NaN,Port,Portugal,Porto,4.4,10
p0401,Quinta do Noval,Vintage Port N.V.,"{'average': '4.4', 'reviews': '1018 ratings'}",Portugal\n·\nVintage Port,https://images.vivino.com/thumbs/y9P75uaVT6yoG...,NaN,Port,Portugal,Vintage Port,4.4,10
p0402,Royal Oporto,20 Year Old Tawny Porto N.V.,"{'average': '4.4', 'reviews': '898 ratings'}",Portugal\n·\nAged Tawny Port,https://images.vivino.com/thumbs/4usgrqCrTUKag...,NaN,Port,Portugal,Aged Tawny Port,4.4,89
p0403,Royal Oporto,Colheita Porto N.V.,"{'average': '4.4', 'reviews': '881 ratings'}",Portugal\n·\nColheita Port,https://images.vivino.com/thumbs/QnSyShsLRguoG...,NaN,Port,Portugal,Colheita Port,4.4,88

In [81]:
# removing 'rating' and 'location' columns
del wine_df['rating']
del wine_df['location']
del wine_df['average']

In [82]:
# checking dataframe
wine_df

,winery,wine,image,wine type,country,region,average rating,review count
id,,,,,,,,
r0001,Maselva,Emporda 2012,https://images.vivino.com/thumbs/ApnIiXjcT5Kc3...,Red,Spain,Empordà,4.9,88
r0002,Ernesto Ruffo,Amarone della Valpolicella Riserva N.V.,https://images.vivino.com/thumbs/nC9V6L2mQQSq0...,Red,Italy,Amarone della Valpolicella,4.9,75
r0003,Cartuxa,Pêra-Manca Tinto 1990,https://images.vivino.com/thumbs/L33jsYUuTMWTM...,Red,Portugal,Alentejo,4.9,72
r0004,Schrader,Cabernet Sauvignon RBS Beckstoffer To Kalon Vi...,https://images.vivino.com/thumbs/GpcSXs2ERS6ni...,Red,United States,Oakville,4.9,72
r0005,Hundred Acre,Wraith Cabernet Sauvignon 2013,https://images.vivino.com/thumbs/PBhGMcRNQ7aVn...,Red,United States,Napa Valley,4.9,68
...,...,...,...,...,...,...,...,...
p0399,Toro Albalá,Don PX Gran Reserva 1986,https://images.vivino.com/thumbs/qAad7NzITH-si...,Port,Spain,Montilla-Moriles,4.4,10
p0400,Quinta do Vallado,Porto 20 Years Old Tawny N.V.,https://images.vivino.com/thumbs/jHGhovW_QZ6b4...,Port,Portugal,Porto,4.4,10
p0401,Quinta do Noval,Vintage Port N.V.,https://images.vivino.com/thumbs/y9P75uaVT6yoG...,Port,Portugal,Vintage Port,4.4,10
p0402,Royal Oporto,20 Year Old Tawny Porto N.V.,https://images.vivino.com/thumbs/4usgrqCrTUKag...,Port,Portugal,Aged Tawny Port,4.4,89
p0403,Royal Oporto,Colheita Porto N.V.,https://images.vivino.com/thumbs/QnSyShsLRguoG...,Port,Portugal,Colheita Port,4.4,88

In [83]:
# getting a list of the unique wineries in the dataframe
wineryList = wine_df['winery'].unique()
len(wineryList)

1010

In [84]:
# creating a winery_df
wineryID = ['v'+'{:0>5}'.format(str(id+1)) for id in range(len(wineryList))]
winery_df = pd.DataFrame({'winery id':wineryID,'winery':wineryList})
winery_df

     winery id                             winery
0       v00001                            Maselva
1       v00002                      Ernesto Ruffo
2       v00003                            Cartuxa
3       v00004                           Schrader
4       v00005                       Hundred Acre
...        ...                                ...
1005    v01006                          Augusto's
1006    v01007  Hutcheson Feuerheerd & Associados
1007    v01008                  Quinta de S. José
1008    v01009                     Alves de Sousa
1009    v01010                        Wine & Soul

[1010 rows x 2 columns]

In [85]:
#getting a list of the unique countries in the dataframe
countryList = wine_df['country'].unique()
len(countryList)

26

In [86]:
# creating a country_df
countryID = ['c'+'{:0>3}'.format(str(id+1)) for id in range(len(countryList))]
country_df = pd.DataFrame({'country id':countryID,'country':countryList})
country_df

   country id        country
0        c001          Spain
1        c002          Italy
2        c003       Portugal
3        c004  United States
4        c005         France
5        c006
6        c007      Argentina
7        c008   South Africa
8        c009        Hungary
9        c010      Australia
10       c011          Chile
11       c012        Austria
12       c013      Macedonia
13       c014         Canada
14       c015        Germany
15       c016        Romania
16       c017    Switzerland
17       c018    New Zealand
18       c019       Slovenia
19       c020        Georgia
20       c021         Greece
21       c022         Israel
22       c023         Turkey
23       c024        Moldova
24       c025         Brazil
25       c026        Uruguay

In [87]:
#getting a list of the unique regions in the dataframe
regionList = wine_df['region'].unique()
len(regionList)

392

In [88]:
#creating a region_df
regionID = ['a'+'{:0>4}'.format(str(id+1)) for id in range(len(regionList))]
region_df = pd.DataFrame({'region id':regionID,'region':regionList})
region_df

    region id                      region
0       a0001                     Empordà
1       a0002  Amarone della Valpolicella
2       a0003                    Alentejo
3       a0004                    Oakville
4       a0005                 Napa Valley
..        ...                         ...
387     a0388          Amontillado Sherry
388     a0389        Muscat de Rivesaltes
389     a0390              Oloroso Sherry
390     a0391                     Barossa
391     a0392           Banyuls Grand Cru

[392 rows x 2 columns]

In [89]:
# getting a list of the wine types
wineTypeList = wine_df['wine type'].unique()
len(wineTypeList)

6

In [90]:
# creating a wineType_df
wineTypeID = ['t'+str(id+1) for id in range(len(wineTypeList))]
wineType_df = pd.DataFrame({'wine type id':wineTypeID,'wine type':wineTypeList})
wineType_df

  wine type id  wine type
0           t1        Red
1           t2      White
2           t3       Rose
3           t4  Sparkling
4           t5    Dessert
5           t6       Port

In [91]:
wine_df.to_csv('wine.csv', index = True)
winery_df.to_csv('winery.csv', index = False)
wineType_df.to_csv('wine_type.csv', index = False)
region_df.to_csv('region.csv', index = False)
country_df.to_csv('country.csv', index = False)

In [92]:
varietalLs = ['Pinot Noir', 'Cabernet Sauvignon', 'Merlot', 'Syrah', 'Malbec', 'Grenache', 'Chardonnay', 'Sauvignon Blanc', 'Riesling', 'Pinot Gris', 'Chenin Blanc', 'Moscato', 'Albariño', 'Viognier','Prosecco', 'Blanc de Noir', "Blanc de Blancs", 'Champagne', 'Cava','Gamay']

In [93]:
import re

In [94]:
# reasign Dfs (avoid timeout with API)
wineDf = pd.read_csv('wine.csv', index_col = 'id')

In [96]:
# 
filteredDf = wineDf[wineDf['wine'].str.contains('|'.join(varietalLs))]

In [97]:
# define the regular expression pattern for the varietals
pattern = rf"\b({'|'.join(varietalLs)})\b"

# use str.extract to extract the varietal from the "wine" column
filteredDf['varietal'] = filteredDf['wine'].str.extract(pattern, flags=re.IGNORECASE)

C:\Users\edwar\AppData\Local\Temp\ipykernel_3484\2170820923.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredDf['varietal'] = filteredDf['wine'].str.extract(pattern, flags=re.IGNORECASE)

In [99]:
filteredDf.head()

,winery,wine,image,wine type,country,region,average rating,review count,varietal
id,,,,,,,,,
r0004,Schrader,Cabernet Sauvignon RBS Beckstoffer To Kalon Vi...,https://images.vivino.com/thumbs/GpcSXs2ERS6ni...,Red,United States,Oakville,4.9,72,Cabernet Sauvignon
r0005,Hundred Acre,Wraith Cabernet Sauvignon 2013,https://images.vivino.com/thumbs/PBhGMcRNQ7aVn...,Red,United States,Napa Valley,4.9,68,Cabernet Sauvignon
r0006,Sine Qua Non,Ratsel Syrah N.V.,https://images.vivino.com/thumbs/ZzMKzqFqRO-6o...,Red,United States,California,4.9,68,Syrah
r0007,Del Dotto,The Beast Cabernet Sauvignon 2012,https://images.vivino.com/thumbs/easjTPIcS-mCQ...,Red,United States,Rutherford,4.9,60,Cabernet Sauvignon
r0008,Darioush,Darius II Cabernet Sauvignon 2016,https://images.vivino.com/thumbs/U19RXtSdRMmoA...,Red,United States,Napa Valley,4.9,59,Cabernet Sauvignon